name = "LocalFDR"
uuid = "4d43c0f7-3473-4d95-ac58-f96eaf045327"
authors = ["kshedden <kshedden@umich.edu>"]
version = "0.1.0"

[deps]
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
GLM = "1.9.0"
LinearAlgebra = "1.11.0"
